version: "3"
services:

  unilog:
    environment:
      - WAIT_FOR_DEPS=true
    volumes:
      - ./dev:/app/dev
      - ./dev/dev-config.edn:/etc/config/akvo-unilog/config.edn
    image: "eu.gcr.io/${PROJECT_NAME}/akvo-unilog:$TRAVIS_COMMIT"

  tests:
    image: akvo-unilog-dev:develop
    network_mode: service:mainnetwork
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
      - pg-data:/pg-certs:ro
    depends_on:
      - unilog
    command: tail -f /dev/null
    environment:
      - PGSSLROOTCERT=/pg-certs/server.crt
