# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "unilog-dev-20150424"
  config.vm.box_url = "http://files.akvo-ops.org/unilog-dev-20150605.box"

  config.vm.synced_folder "../", "/vagrant/unilog/checkout/", 
    :owner => "unilog", 
    :group => "unilog"

  config.vm.synced_folder "../../akvo-flow-server-config/", "/vagrant/flow-server-config/checkout/",
    :owner => "unilog",
    :group => "unilog"

  config.vm.network :private_network, ip: "192.168.50.101"

  config.vm.provision "shell", run: "always", path: "./provisioning/link_code.sh"
  config.vm.provision "shell", run: "always", path: "./provisioning/initialize_db.sh"
  config.vm.provision "shell", run: "always", path: "./provisioning/run_service.sh"

end
